local RankConfig = {}

RankConfig.Ranks = {
	["Unrank"] = {
		MapName = "Tutorial",
		BaseHP = 100,
		PowerTestScore = 0
	},
	["F"] = {
		MapName = "FZone",
		BaseHP = 160,
		PowerTestScore = 1600
	},
	["E"] = {
		MapName = "EZone",
		BaseHP = 600,
		PowerTestScore = 4000
	},
	["D"] = {
		MapName = "DZone",
		BaseHP = 2000,
		PowerTestScore = 10000
	},
	["C"] = {
		MapName = "CZone",
		BaseHP = 6000,
		PowerTestScore = 24000
	},
	["B"] = {
		MapName = "BZone",
		BaseHP = 18000,
		PowerTestScore = 60000
	},
	["A"] = {
		MapName = "AZone",
		BaseHP = 49000,
		PowerTestScore = 140000
	},
	["S"] = {
		MapName = "SZone",
		BaseHP = 128000,
		PowerTestScore = 320000
	},
	["SS"] = {
		MapName = "SSZone",
		BaseHP = 315000,
		PowerTestScore = 700000
	},
	["SSS"] = {
		MapName = "SSSZone",
		BaseHP = 800000,
		PowerTestScore = 1600000
	},
}

return RankConfig