local SoundConfig = {

-- --------------------
-- 공격 사운드
-----------------------------
	--Hit_Wall
	Hit_Wall_01 = {
		Id = "rbxassetid://88004088808545",
		Volume = 0.9
	},

	--fire_punch_finisher_06
	Hit_Wall_02 = {
		Id = "rbxassetid://136596691924191",
		Volume = 0.9
	},
	
	--Explosion 3_[cut_1sec]
	Hit_Wall_03 = {
		Id = "rbxassetid://104757805277561",
		Volume = 0.9
	},
	
	--face_hit_small_78
	Hit_Wall_04 = {
		Id = "rbxassetid://84428333576422",
		Volume = 0.9
	},
	
	--body_hit_large_32
	Hit_Wall_05 = {
		Id = "rbxassetid://86077248060145",
		Volume = 0.9
	},
	
	--61_Hit_03
	Hit_Wall_06 = {
		Id = "rbxassetid://129490577130502",
		Volume = 0.9
	},
	
	--Break_Wall
	Break_Wall = {
		Id = "rbxassetid://85784528131423",
		Volume = 0.65
	},
---------------------------------------------

-- --------------------
-- UI 사운드
-----------------------------

	--001_Hover_01
	Panel_Open = {
		Id = "rbxassetid://73259012332777",
		Volume = 0.9
	},
	
	--013_Confirm_03
	Panel_Confirm = {
		Id = "rbxassetid://107081628073591",
		Volume = 0.9
	},
	
	--029_Decline_09
	Panel_Cancel = {
		Id = "rbxassetid://134371852996004",
		Volume = 0.9
	},
	
	
	--098_Unpause_04
	Panel_Close = {
		Id = "rbxassetid://118335231620317",
		Volume = 0.9
	},
	
	--EquipPet
	Equip_Pet = {
		Id = "rbxassetid://125338128309434",
		Volume = 0.9
	},
	
	--UnequipPet
	Unequip_Pet = {
		Id = "rbxassetid://109305960202738",
		Volume = 0.9
	},
	
	--GachaSound
	Gacha_Pick = {
		Id = "rbxassetid://138860419699067",
		Volume = 0.9
	},
	
	--Button_Click_02
	Button_Click = {
		Id = "rbxassetid://74370485485779",
		Volume = 0.9
	},
	
	--Fail_Sound
	Purchase_Fail = {
		Id = "rbxassetid://85783770905085",
		Volume = 0.65
	},
	
	--Teleport_Sound
	Teleport_Sound = {
		Id = "rbxassetid://116734008834559",
		Volume = 0.9
	},
	
	--Tribal Drum
	PowertestResult_Sound = {
		Id = "rbxassetid://88652888681632",
		Volume = 0.9
	},
}

return SoundConfig